<?php

/*
 * This file is part of the ixnode/php-timezone project.
 *
 * (c) Björn Hempel <https://www.hempel.li/>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Ixnode\PhpTimezone\Constants;

/**
 * Class CountryAll (auto-generated with bin/build-countries from "data/africa.csv, data/antarctica.csv, data/asia.csv, data/australia.csv, data/europe.csv, data/north-america.csv, data/south-america.csv")
 *
 * @author Björn Hempel <bjoern@hempel.li>
 * @version 0.1.0 (2024-05-22 18:59:55)
 * @since 0.1.0 (2024-05-22 18:59:55) Generated version.
 */
class CountryAll
{
    public const COUNTRY_NAMES = [

        /* Africa */
        CountryAfrica::COUNTRY_CODE_DZ => CountryAfrica::COUNTRY_NAME_DZ,
        CountryAfrica::COUNTRY_CODE_AO => CountryAfrica::COUNTRY_NAME_AO,
        CountryAfrica::COUNTRY_CODE_SH => CountryAfrica::COUNTRY_NAME_SH,
        CountryAfrica::COUNTRY_CODE_BJ => CountryAfrica::COUNTRY_NAME_BJ,
        CountryAfrica::COUNTRY_CODE_BW => CountryAfrica::COUNTRY_NAME_BW,
        CountryAfrica::COUNTRY_CODE_BF => CountryAfrica::COUNTRY_NAME_BF,
        CountryAfrica::COUNTRY_CODE_BI => CountryAfrica::COUNTRY_NAME_BI,
        CountryAfrica::COUNTRY_CODE_CM => CountryAfrica::COUNTRY_NAME_CM,
        CountryAfrica::COUNTRY_CODE_CV => CountryAfrica::COUNTRY_NAME_CV,
        CountryAfrica::COUNTRY_CODE_CF => CountryAfrica::COUNTRY_NAME_CF,
        CountryAfrica::COUNTRY_CODE_TD => CountryAfrica::COUNTRY_NAME_TD,
        CountryAfrica::COUNTRY_CODE_KM => CountryAfrica::COUNTRY_NAME_KM,
        CountryAfrica::COUNTRY_CODE_CG => CountryAfrica::COUNTRY_NAME_CG,
        CountryAfrica::COUNTRY_CODE_DJ => CountryAfrica::COUNTRY_NAME_DJ,
        CountryAfrica::COUNTRY_CODE_EG => CountryAfrica::COUNTRY_NAME_EG,
        CountryAfrica::COUNTRY_CODE_GQ => CountryAfrica::COUNTRY_NAME_GQ,
        CountryAfrica::COUNTRY_CODE_ER => CountryAfrica::COUNTRY_NAME_ER,
        CountryAfrica::COUNTRY_CODE_ET => CountryAfrica::COUNTRY_NAME_ET,
        CountryAfrica::COUNTRY_CODE_GA => CountryAfrica::COUNTRY_NAME_GA,
        CountryAfrica::COUNTRY_CODE_GM => CountryAfrica::COUNTRY_NAME_GM,
        CountryAfrica::COUNTRY_CODE_GH => CountryAfrica::COUNTRY_NAME_GH,
        CountryAfrica::COUNTRY_CODE_GW => CountryAfrica::COUNTRY_NAME_GW,
        CountryAfrica::COUNTRY_CODE_GN => CountryAfrica::COUNTRY_NAME_GN,
        CountryAfrica::COUNTRY_CODE_CI => CountryAfrica::COUNTRY_NAME_CI,
        CountryAfrica::COUNTRY_CODE_KE => CountryAfrica::COUNTRY_NAME_KE,
        CountryAfrica::COUNTRY_CODE_LS => CountryAfrica::COUNTRY_NAME_LS,
        CountryAfrica::COUNTRY_CODE_LR => CountryAfrica::COUNTRY_NAME_LR,
        CountryAfrica::COUNTRY_CODE_LY => CountryAfrica::COUNTRY_NAME_LY,
        CountryAfrica::COUNTRY_CODE_MG => CountryAfrica::COUNTRY_NAME_MG,
        CountryAfrica::COUNTRY_CODE_MW => CountryAfrica::COUNTRY_NAME_MW,
        CountryAfrica::COUNTRY_CODE_ML => CountryAfrica::COUNTRY_NAME_ML,
        CountryAfrica::COUNTRY_CODE_MR => CountryAfrica::COUNTRY_NAME_MR,
        CountryAfrica::COUNTRY_CODE_MU => CountryAfrica::COUNTRY_NAME_MU,
        CountryAfrica::COUNTRY_CODE_YT => CountryAfrica::COUNTRY_NAME_YT,
        CountryAfrica::COUNTRY_CODE_MA => CountryAfrica::COUNTRY_NAME_MA,
        CountryAfrica::COUNTRY_CODE_MZ => CountryAfrica::COUNTRY_NAME_MZ,
        CountryAfrica::COUNTRY_CODE_NA => CountryAfrica::COUNTRY_NAME_NA,
        CountryAfrica::COUNTRY_CODE_NE => CountryAfrica::COUNTRY_NAME_NE,
        CountryAfrica::COUNTRY_CODE_NG => CountryAfrica::COUNTRY_NAME_NG,
        CountryAfrica::COUNTRY_CODE_ST => CountryAfrica::COUNTRY_NAME_ST,
        CountryAfrica::COUNTRY_CODE_RE => CountryAfrica::COUNTRY_NAME_RE,
        CountryAfrica::COUNTRY_CODE_RW => CountryAfrica::COUNTRY_NAME_RW,
        CountryAfrica::COUNTRY_CODE_SN => CountryAfrica::COUNTRY_NAME_SN,
        CountryAfrica::COUNTRY_CODE_SC => CountryAfrica::COUNTRY_NAME_SC,
        CountryAfrica::COUNTRY_CODE_SL => CountryAfrica::COUNTRY_NAME_SL,
        CountryAfrica::COUNTRY_CODE_SO => CountryAfrica::COUNTRY_NAME_SO,
        CountryAfrica::COUNTRY_CODE_ZA => CountryAfrica::COUNTRY_NAME_ZA,
        CountryAfrica::COUNTRY_CODE_SD => CountryAfrica::COUNTRY_NAME_SD,
        CountryAfrica::COUNTRY_CODE_SZ => CountryAfrica::COUNTRY_NAME_SZ,
        CountryAfrica::COUNTRY_CODE_TZ => CountryAfrica::COUNTRY_NAME_TZ,
        CountryAfrica::COUNTRY_CODE_TG => CountryAfrica::COUNTRY_NAME_TG,
        CountryAfrica::COUNTRY_CODE_TN => CountryAfrica::COUNTRY_NAME_TN,
        CountryAfrica::COUNTRY_CODE_UG => CountryAfrica::COUNTRY_NAME_UG,
        CountryAfrica::COUNTRY_CODE_CD => CountryAfrica::COUNTRY_NAME_CD,
        CountryAfrica::COUNTRY_CODE_ZM => CountryAfrica::COUNTRY_NAME_ZM,
        CountryAfrica::COUNTRY_CODE_ZW => CountryAfrica::COUNTRY_NAME_ZW,
        CountryAfrica::COUNTRY_CODE_SS => CountryAfrica::COUNTRY_NAME_SS,
        CountryAfrica::COUNTRY_CODE_EH => CountryAfrica::COUNTRY_NAME_EH,

        /* Antarctica */
        CountryAntarctica::COUNTRY_CODE_AQ => CountryAntarctica::COUNTRY_NAME_AQ,

        /* Asia */
        CountryAsia::COUNTRY_CODE_AF => CountryAsia::COUNTRY_NAME_AF,
        CountryAsia::COUNTRY_CODE_AM => CountryAsia::COUNTRY_NAME_AM,
        CountryAsia::COUNTRY_CODE_AZ => CountryAsia::COUNTRY_NAME_AZ,
        CountryAsia::COUNTRY_CODE_BH => CountryAsia::COUNTRY_NAME_BH,
        CountryAsia::COUNTRY_CODE_BD => CountryAsia::COUNTRY_NAME_BD,
        CountryAsia::COUNTRY_CODE_BT => CountryAsia::COUNTRY_NAME_BT,
        CountryAsia::COUNTRY_CODE_BN => CountryAsia::COUNTRY_NAME_BN,
        CountryAsia::COUNTRY_CODE_KH => CountryAsia::COUNTRY_NAME_KH,
        CountryAsia::COUNTRY_CODE_CN => CountryAsia::COUNTRY_NAME_CN,
        CountryAsia::COUNTRY_CODE_CX => CountryAsia::COUNTRY_NAME_CX,
        CountryAsia::COUNTRY_CODE_CC => CountryAsia::COUNTRY_NAME_CC,
        CountryAsia::COUNTRY_CODE_IO => CountryAsia::COUNTRY_NAME_IO,
        CountryAsia::COUNTRY_CODE_GE => CountryAsia::COUNTRY_NAME_GE,
        CountryAsia::COUNTRY_CODE_HK => CountryAsia::COUNTRY_NAME_HK,
        CountryAsia::COUNTRY_CODE_IN => CountryAsia::COUNTRY_NAME_IN,
        CountryAsia::COUNTRY_CODE_ID => CountryAsia::COUNTRY_NAME_ID,
        CountryAsia::COUNTRY_CODE_IR => CountryAsia::COUNTRY_NAME_IR,
        CountryAsia::COUNTRY_CODE_IQ => CountryAsia::COUNTRY_NAME_IQ,
        CountryAsia::COUNTRY_CODE_IL => CountryAsia::COUNTRY_NAME_IL,
        CountryAsia::COUNTRY_CODE_JP => CountryAsia::COUNTRY_NAME_JP,
        CountryAsia::COUNTRY_CODE_JO => CountryAsia::COUNTRY_NAME_JO,
        CountryAsia::COUNTRY_CODE_KZ => CountryAsia::COUNTRY_NAME_KZ,
        CountryAsia::COUNTRY_CODE_KP => CountryAsia::COUNTRY_NAME_KP,
        CountryAsia::COUNTRY_CODE_KR => CountryAsia::COUNTRY_NAME_KR,
        CountryAsia::COUNTRY_CODE_KW => CountryAsia::COUNTRY_NAME_KW,
        CountryAsia::COUNTRY_CODE_KG => CountryAsia::COUNTRY_NAME_KG,
        CountryAsia::COUNTRY_CODE_LA => CountryAsia::COUNTRY_NAME_LA,
        CountryAsia::COUNTRY_CODE_LB => CountryAsia::COUNTRY_NAME_LB,
        CountryAsia::COUNTRY_CODE_MO => CountryAsia::COUNTRY_NAME_MO,
        CountryAsia::COUNTRY_CODE_MY => CountryAsia::COUNTRY_NAME_MY,
        CountryAsia::COUNTRY_CODE_MV => CountryAsia::COUNTRY_NAME_MV,
        CountryAsia::COUNTRY_CODE_MN => CountryAsia::COUNTRY_NAME_MN,
        CountryAsia::COUNTRY_CODE_MM => CountryAsia::COUNTRY_NAME_MM,
        CountryAsia::COUNTRY_CODE_NP => CountryAsia::COUNTRY_NAME_NP,
        CountryAsia::COUNTRY_CODE_OM => CountryAsia::COUNTRY_NAME_OM,
        CountryAsia::COUNTRY_CODE_PK => CountryAsia::COUNTRY_NAME_PK,
        CountryAsia::COUNTRY_CODE_PH => CountryAsia::COUNTRY_NAME_PH,
        CountryAsia::COUNTRY_CODE_QA => CountryAsia::COUNTRY_NAME_QA,
        CountryAsia::COUNTRY_CODE_SA => CountryAsia::COUNTRY_NAME_SA,
        CountryAsia::COUNTRY_CODE_SG => CountryAsia::COUNTRY_NAME_SG,
        CountryAsia::COUNTRY_CODE_LK => CountryAsia::COUNTRY_NAME_LK,
        CountryAsia::COUNTRY_CODE_SY => CountryAsia::COUNTRY_NAME_SY,
        CountryAsia::COUNTRY_CODE_TW => CountryAsia::COUNTRY_NAME_TW,
        CountryAsia::COUNTRY_CODE_TJ => CountryAsia::COUNTRY_NAME_TJ,
        CountryAsia::COUNTRY_CODE_TH => CountryAsia::COUNTRY_NAME_TH,
        CountryAsia::COUNTRY_CODE_TR => CountryAsia::COUNTRY_NAME_TR,
        CountryAsia::COUNTRY_CODE_TM => CountryAsia::COUNTRY_NAME_TM,
        CountryAsia::COUNTRY_CODE_AE => CountryAsia::COUNTRY_NAME_AE,
        CountryAsia::COUNTRY_CODE_UZ => CountryAsia::COUNTRY_NAME_UZ,
        CountryAsia::COUNTRY_CODE_VN => CountryAsia::COUNTRY_NAME_VN,
        CountryAsia::COUNTRY_CODE_YE => CountryAsia::COUNTRY_NAME_YE,
        CountryAsia::COUNTRY_CODE_PS => CountryAsia::COUNTRY_NAME_PS,

        /* Australia */
        CountryAustralia::COUNTRY_CODE_AS => CountryAustralia::COUNTRY_NAME_AS,
        CountryAustralia::COUNTRY_CODE_AU => CountryAustralia::COUNTRY_NAME_AU,
        CountryAustralia::COUNTRY_CODE_NZ => CountryAustralia::COUNTRY_NAME_NZ,
        CountryAustralia::COUNTRY_CODE_CK => CountryAustralia::COUNTRY_NAME_CK,
        CountryAustralia::COUNTRY_CODE_FJ => CountryAustralia::COUNTRY_NAME_FJ,
        CountryAustralia::COUNTRY_CODE_PF => CountryAustralia::COUNTRY_NAME_PF,
        CountryAustralia::COUNTRY_CODE_GU => CountryAustralia::COUNTRY_NAME_GU,
        CountryAustralia::COUNTRY_CODE_KI => CountryAustralia::COUNTRY_NAME_KI,
        CountryAustralia::COUNTRY_CODE_MP => CountryAustralia::COUNTRY_NAME_MP,
        CountryAustralia::COUNTRY_CODE_MH => CountryAustralia::COUNTRY_NAME_MH,
        CountryAustralia::COUNTRY_CODE_FM => CountryAustralia::COUNTRY_NAME_FM,
        CountryAustralia::COUNTRY_CODE_UM => CountryAustralia::COUNTRY_NAME_UM,
        CountryAustralia::COUNTRY_CODE_NR => CountryAustralia::COUNTRY_NAME_NR,
        CountryAustralia::COUNTRY_CODE_NC => CountryAustralia::COUNTRY_NAME_NC,
        CountryAustralia::COUNTRY_CODE_NU => CountryAustralia::COUNTRY_NAME_NU,
        CountryAustralia::COUNTRY_CODE_NF => CountryAustralia::COUNTRY_NAME_NF,
        CountryAustralia::COUNTRY_CODE_PW => CountryAustralia::COUNTRY_NAME_PW,
        CountryAustralia::COUNTRY_CODE_PG => CountryAustralia::COUNTRY_NAME_PG,
        CountryAustralia::COUNTRY_CODE_SB => CountryAustralia::COUNTRY_NAME_SB,
        CountryAustralia::COUNTRY_CODE_TK => CountryAustralia::COUNTRY_NAME_TK,
        CountryAustralia::COUNTRY_CODE_TO => CountryAustralia::COUNTRY_NAME_TO,
        CountryAustralia::COUNTRY_CODE_TV => CountryAustralia::COUNTRY_NAME_TV,
        CountryAustralia::COUNTRY_CODE_VU => CountryAustralia::COUNTRY_NAME_VU,
        CountryAustralia::COUNTRY_CODE_WF => CountryAustralia::COUNTRY_NAME_WF,
        CountryAustralia::COUNTRY_CODE_WS => CountryAustralia::COUNTRY_NAME_WS,
        CountryAustralia::COUNTRY_CODE_TL => CountryAustralia::COUNTRY_NAME_TL,

        /* Europe */
        CountryEurope::COUNTRY_CODE_AL => CountryEurope::COUNTRY_NAME_AL,
        CountryEurope::COUNTRY_CODE_AD => CountryEurope::COUNTRY_NAME_AD,
        CountryEurope::COUNTRY_CODE_AT => CountryEurope::COUNTRY_NAME_AT,
        CountryEurope::COUNTRY_CODE_AX => CountryEurope::COUNTRY_NAME_AX,
        CountryEurope::COUNTRY_CODE_BY => CountryEurope::COUNTRY_NAME_BY,
        CountryEurope::COUNTRY_CODE_BE => CountryEurope::COUNTRY_NAME_BE,
        CountryEurope::COUNTRY_CODE_BA => CountryEurope::COUNTRY_NAME_BA,
        CountryEurope::COUNTRY_CODE_BG => CountryEurope::COUNTRY_NAME_BG,
        CountryEurope::COUNTRY_CODE_HR => CountryEurope::COUNTRY_NAME_HR,
        CountryEurope::COUNTRY_CODE_CY => CountryEurope::COUNTRY_NAME_CY,
        CountryEurope::COUNTRY_CODE_CZ => CountryEurope::COUNTRY_NAME_CZ,
        CountryEurope::COUNTRY_CODE_DK => CountryEurope::COUNTRY_NAME_DK,
        CountryEurope::COUNTRY_CODE_EE => CountryEurope::COUNTRY_NAME_EE,
        CountryEurope::COUNTRY_CODE_FO => CountryEurope::COUNTRY_NAME_FO,
        CountryEurope::COUNTRY_CODE_FI => CountryEurope::COUNTRY_NAME_FI,
        CountryEurope::COUNTRY_CODE_FR => CountryEurope::COUNTRY_NAME_FR,
        CountryEurope::COUNTRY_CODE_DE => CountryEurope::COUNTRY_NAME_DE,
        CountryEurope::COUNTRY_CODE_GI => CountryEurope::COUNTRY_NAME_GI,
        CountryEurope::COUNTRY_CODE_GR => CountryEurope::COUNTRY_NAME_GR,
        CountryEurope::COUNTRY_CODE_HU => CountryEurope::COUNTRY_NAME_HU,
        CountryEurope::COUNTRY_CODE_IS => CountryEurope::COUNTRY_NAME_IS,
        CountryEurope::COUNTRY_CODE_IE => CountryEurope::COUNTRY_NAME_IE,
        CountryEurope::COUNTRY_CODE_IT => CountryEurope::COUNTRY_NAME_IT,
        CountryEurope::COUNTRY_CODE_LV => CountryEurope::COUNTRY_NAME_LV,
        CountryEurope::COUNTRY_CODE_LI => CountryEurope::COUNTRY_NAME_LI,
        CountryEurope::COUNTRY_CODE_LT => CountryEurope::COUNTRY_NAME_LT,
        CountryEurope::COUNTRY_CODE_LU => CountryEurope::COUNTRY_NAME_LU,
        CountryEurope::COUNTRY_CODE_MK => CountryEurope::COUNTRY_NAME_MK,
        CountryEurope::COUNTRY_CODE_MT => CountryEurope::COUNTRY_NAME_MT,
        CountryEurope::COUNTRY_CODE_MD => CountryEurope::COUNTRY_NAME_MD,
        CountryEurope::COUNTRY_CODE_MC => CountryEurope::COUNTRY_NAME_MC,
        CountryEurope::COUNTRY_CODE_NL => CountryEurope::COUNTRY_NAME_NL,
        CountryEurope::COUNTRY_CODE_NO => CountryEurope::COUNTRY_NAME_NO,
        CountryEurope::COUNTRY_CODE_PL => CountryEurope::COUNTRY_NAME_PL,
        CountryEurope::COUNTRY_CODE_PT => CountryEurope::COUNTRY_NAME_PT,
        CountryEurope::COUNTRY_CODE_RO => CountryEurope::COUNTRY_NAME_RO,
        CountryEurope::COUNTRY_CODE_RU => CountryEurope::COUNTRY_NAME_RU,
        CountryEurope::COUNTRY_CODE_SM => CountryEurope::COUNTRY_NAME_SM,
        CountryEurope::COUNTRY_CODE_RS => CountryEurope::COUNTRY_NAME_RS,
        CountryEurope::COUNTRY_CODE_SK => CountryEurope::COUNTRY_NAME_SK,
        CountryEurope::COUNTRY_CODE_SI => CountryEurope::COUNTRY_NAME_SI,
        CountryEurope::COUNTRY_CODE_ES => CountryEurope::COUNTRY_NAME_ES,
        CountryEurope::COUNTRY_CODE_SE => CountryEurope::COUNTRY_NAME_SE,
        CountryEurope::COUNTRY_CODE_CH => CountryEurope::COUNTRY_NAME_CH,
        CountryEurope::COUNTRY_CODE_UA => CountryEurope::COUNTRY_NAME_UA,
        CountryEurope::COUNTRY_CODE_GB => CountryEurope::COUNTRY_NAME_GB,
        CountryEurope::COUNTRY_CODE_VA => CountryEurope::COUNTRY_NAME_VA,
        CountryEurope::COUNTRY_CODE_IM => CountryEurope::COUNTRY_NAME_IM,
        CountryEurope::COUNTRY_CODE_ME => CountryEurope::COUNTRY_NAME_ME,
        CountryEurope::COUNTRY_CODE_XK => CountryEurope::COUNTRY_NAME_XK,

        /* North America */
        CountryNorthAmerica::COUNTRY_CODE_AI => CountryNorthAmerica::COUNTRY_NAME_AI,
        CountryNorthAmerica::COUNTRY_CODE_AG => CountryNorthAmerica::COUNTRY_NAME_AG,
        CountryNorthAmerica::COUNTRY_CODE_AW => CountryNorthAmerica::COUNTRY_NAME_AW,
        CountryNorthAmerica::COUNTRY_CODE_BS => CountryNorthAmerica::COUNTRY_NAME_BS,
        CountryNorthAmerica::COUNTRY_CODE_BB => CountryNorthAmerica::COUNTRY_NAME_BB,
        CountryNorthAmerica::COUNTRY_CODE_BZ => CountryNorthAmerica::COUNTRY_NAME_BZ,
        CountryNorthAmerica::COUNTRY_CODE_BM => CountryNorthAmerica::COUNTRY_NAME_BM,
        CountryNorthAmerica::COUNTRY_CODE_VG => CountryNorthAmerica::COUNTRY_NAME_VG,
        CountryNorthAmerica::COUNTRY_CODE_CA => CountryNorthAmerica::COUNTRY_NAME_CA,
        CountryNorthAmerica::COUNTRY_CODE_KY => CountryNorthAmerica::COUNTRY_NAME_KY,
        CountryNorthAmerica::COUNTRY_CODE_CR => CountryNorthAmerica::COUNTRY_NAME_CR,
        CountryNorthAmerica::COUNTRY_CODE_CU => CountryNorthAmerica::COUNTRY_NAME_CU,
        CountryNorthAmerica::COUNTRY_CODE_CW => CountryNorthAmerica::COUNTRY_NAME_CW,
        CountryNorthAmerica::COUNTRY_CODE_DM => CountryNorthAmerica::COUNTRY_NAME_DM,
        CountryNorthAmerica::COUNTRY_CODE_DO => CountryNorthAmerica::COUNTRY_NAME_DO,
        CountryNorthAmerica::COUNTRY_CODE_SV => CountryNorthAmerica::COUNTRY_NAME_SV,
        CountryNorthAmerica::COUNTRY_CODE_GL => CountryNorthAmerica::COUNTRY_NAME_GL,
        CountryNorthAmerica::COUNTRY_CODE_GD => CountryNorthAmerica::COUNTRY_NAME_GD,
        CountryNorthAmerica::COUNTRY_CODE_GP => CountryNorthAmerica::COUNTRY_NAME_GP,
        CountryNorthAmerica::COUNTRY_CODE_GT => CountryNorthAmerica::COUNTRY_NAME_GT,
        CountryNorthAmerica::COUNTRY_CODE_HT => CountryNorthAmerica::COUNTRY_NAME_HT,
        CountryNorthAmerica::COUNTRY_CODE_HN => CountryNorthAmerica::COUNTRY_NAME_HN,
        CountryNorthAmerica::COUNTRY_CODE_JM => CountryNorthAmerica::COUNTRY_NAME_JM,
        CountryNorthAmerica::COUNTRY_CODE_MQ => CountryNorthAmerica::COUNTRY_NAME_MQ,
        CountryNorthAmerica::COUNTRY_CODE_MX => CountryNorthAmerica::COUNTRY_NAME_MX,
        CountryNorthAmerica::COUNTRY_CODE_PM => CountryNorthAmerica::COUNTRY_NAME_PM,
        CountryNorthAmerica::COUNTRY_CODE_MS => CountryNorthAmerica::COUNTRY_NAME_MS,
        CountryNorthAmerica::COUNTRY_CODE_KN => CountryNorthAmerica::COUNTRY_NAME_KN,
        CountryNorthAmerica::COUNTRY_CODE_NI => CountryNorthAmerica::COUNTRY_NAME_NI,
        CountryNorthAmerica::COUNTRY_CODE_PA => CountryNorthAmerica::COUNTRY_NAME_PA,
        CountryNorthAmerica::COUNTRY_CODE_PR => CountryNorthAmerica::COUNTRY_NAME_PR,
        CountryNorthAmerica::COUNTRY_CODE_LC => CountryNorthAmerica::COUNTRY_NAME_LC,
        CountryNorthAmerica::COUNTRY_CODE_VC => CountryNorthAmerica::COUNTRY_NAME_VC,
        CountryNorthAmerica::COUNTRY_CODE_TT => CountryNorthAmerica::COUNTRY_NAME_TT,
        CountryNorthAmerica::COUNTRY_CODE_TC => CountryNorthAmerica::COUNTRY_NAME_TC,
        CountryNorthAmerica::COUNTRY_CODE_VI => CountryNorthAmerica::COUNTRY_NAME_VI,
        CountryNorthAmerica::COUNTRY_CODE_US => CountryNorthAmerica::COUNTRY_NAME_US,
        CountryNorthAmerica::COUNTRY_CODE_SX => CountryNorthAmerica::COUNTRY_NAME_SX,
        CountryNorthAmerica::COUNTRY_CODE_BQ => CountryNorthAmerica::COUNTRY_NAME_BQ,

        /* South America */
        CountrySouthAmerica::COUNTRY_CODE_AR => CountrySouthAmerica::COUNTRY_NAME_AR,
        CountrySouthAmerica::COUNTRY_CODE_BO => CountrySouthAmerica::COUNTRY_NAME_BO,
        CountrySouthAmerica::COUNTRY_CODE_BR => CountrySouthAmerica::COUNTRY_NAME_BR,
        CountrySouthAmerica::COUNTRY_CODE_CL => CountrySouthAmerica::COUNTRY_NAME_CL,
        CountrySouthAmerica::COUNTRY_CODE_CO => CountrySouthAmerica::COUNTRY_NAME_CO,
        CountrySouthAmerica::COUNTRY_CODE_EC => CountrySouthAmerica::COUNTRY_NAME_EC,
        CountrySouthAmerica::COUNTRY_CODE_FK => CountrySouthAmerica::COUNTRY_NAME_FK,
        CountrySouthAmerica::COUNTRY_CODE_GF => CountrySouthAmerica::COUNTRY_NAME_GF,
        CountrySouthAmerica::COUNTRY_CODE_GY => CountrySouthAmerica::COUNTRY_NAME_GY,
        CountrySouthAmerica::COUNTRY_CODE_PY => CountrySouthAmerica::COUNTRY_NAME_PY,
        CountrySouthAmerica::COUNTRY_CODE_PE => CountrySouthAmerica::COUNTRY_NAME_PE,
        CountrySouthAmerica::COUNTRY_CODE_SR => CountrySouthAmerica::COUNTRY_NAME_SR,
        CountrySouthAmerica::COUNTRY_CODE_UY => CountrySouthAmerica::COUNTRY_NAME_UY,
        CountrySouthAmerica::COUNTRY_CODE_VE => CountrySouthAmerica::COUNTRY_NAME_VE,

        /* Unknown/Invalid */
        CountryUnknown::COUNTRY_CODE_UK => CountryUnknown::COUNTRY_NAME_UK,
        CountryUnknown::COUNTRY_CODE_IV => CountryUnknown::COUNTRY_NAME_IV,
    ];
}
